export const marketList = [
	{
		name: "KAYAŞ AÇIK SEMT PAZARI",
		province: "KAYAŞ",
		city: "ANKARA",
		state: "MAMAK",
		address: "KAYAŞ MAHALLESİ YOZGAT CADDESİ ÜZERİ",
		day: "Pazar"
	},
	{
		name: "MAMAK KAPALI SEMT PAZARI",
		province: "MİSKET",
		city: "ANKARA",
		state: "MAMAK",
		address: "MİSKET MAHALLESİ 604 SOKAK NO : 2",
		day: "Pazar"
	},
	{
		name: "BATIKENT KAPALI PAZARI",
		province: "BATIKENT",
		city: "ANKARA",
		state: "YENİMAHALLE",
		address: "BATIKENT BAŞKENT BULVARI 1994. SOK. İLE 1995 SOKAK ARASI",
		day: "Pazar"
	},
	{
		name: "YENİMAHALLE PAZAR PAZARI",
		province: "MERKEZ",
		city: "ANKARA",
		state: "YENİMAHALLE",
		address: "YENİMAHALLE İVEDİK CADDESİ ASIM BEY SOK. İLE AŞIK ÇELEBİ SOK.",
		day: "Pazar"
	},
	{
		name: "AYYILDIZ PAZARI",
		province: "PURSAKLAR",
		city: "ANKARA",
		state: "PURSAKLAR",
		address: "Ayyıldız Mahallesi Yunus Emre Sokak",
		day: "Pazar"
	},
	{
		name: "PAZAR TÖREKENT MAHALLESİ SEMT PAZARI",
		province: "SİNCAN",
		city: "ANKARA",
		state: "SİNCAN",
		address: "Törekent Mahallesi 2105/1 Parsel Muhtarlık Binası yanı",
		day: "Pazar"
	},
	{
		name: "100. Yıl Pazarı",
		province: "YÜZÜNCÜYILİŞÇİBLOKLARI",
		city: "ANKARA",
		state: "ÇANKAYA",
		address: "100. Yıl İşçi Blokları 1427. Cad. ile 1516. Cad. Köşesi",
		day: "Pazar"
	},
	{
		name: "Küçükesat Pazarı",
		province: "ESAT",
		city: "ANKARA",
		state: "ÇANKAYA",
		address: "Bağlar Cad. ile Belligün Sokak Köşesi",
		day: "Pazar"
	},
	{
		name: "Hacıkara Semt Pazarı",
		province: "BEYPAZARI",
		city: "ANKARA",
		state: "BEYPAZARI",
		address: "Hacıkara Mahallesi Şehit Ümit Bölükoğlu Cd.-Beypazarı",
		day: "Pazar"
	},
	{
		name: "KUŞCAĞIZ",
		province: "UFUKTEPE",
		city: "ANKARA",
		state: "KEÇİÖREN",
		address: "KUŞCAĞIZ MAHALLESİ TAŞOCAĞI SOKAK",
		day: "Pazar"
	},
	{
		name: "23 NİSAN",
		province: "AKTEPE",
		city: "ANKARA",
		state: "KEÇİÖREN",
		address: "23 NİSAN MAHALLESİ ANAVATAN CADDESİ",
		day: "Pazar"
	},
	{
		name: "HASKÖY",
		province: "KALABA",
		city: "ANKARA",
		state: "KEÇİÖREN",
		address: "SUBAY EVLERİ MAHALLESİ PAŞABAHÇE SOKAK",
		day: "Pazar"
	},
	{
		name: "KARDEŞLER",
		province: "ŞEHİTKUBİLAY",
		city: "ANKARA",
		state: "KEÇİÖREN",
		address: "AYVALI MAHALLESİ 158 SOKAK",
		day: "Pazar"
	},
	{
		name: "FOÇA",
		province: "MERKEZ",
		city: "ANKARA",
		state: "KEÇİÖREN",
		address: "SANATORYUM CADDESİ FOÇA SOKAK",
		day: "Pazar"
	},
	{
		name: "OVACIK",
		province: "BAĞLUM",
		city: "ANKARA",
		state: "KEÇİÖREN",
		address: "OVACIK MAHALLESİ KENDİN YAP SİTESİ ÖNÜ",
		day: "Pazar"
	},
	{
		name: "ÖRNEK",
		province: "YILDIRIMBEYAZIT/DIŞKAPI",
		city: "ANKARA",
		state: "ALTINDAĞ",
		address: "Hızır Reis Caddesi Pamuk Sokak Üzeri",
		day: "Pazar"
	},
	{
		name: "GÜLPINAR",
		province: "HASKÖY",
		city: "ANKARA",
		state: "ALTINDAĞ",
		address: "Yıldıztepe Mah. 166. Cad.No:23",
		day: "Pazar"
	},
	{
		name: "BEŞİKKAYA",
		province: "SİTELER",
		city: "ANKARA",
		state: "ALTINDAĞ",
		address: "Beşikkaya Mahallesi 459-458-461. Sokaklar arası",
		day: "Pazar"
	},
	{
		name: "Zirvekent",
		province: "MAMAK",
		city: "ANKARA",
		state: "MAMAK",
		address: "Kusunlar Mah. TOKİ Blokları içi",
		day: "Pazar"
	},
	{
		name: "PAZAR PINARBAŞI MAHALLESİ SEMT PAZARI",
		province: "SİNCAN",
		city: "ANKARA",
		state: "SİNCAN",
		address: "Pınarbaşı Mahallesi Yaşar Kemal Sokak ile Palamut Sokak Kesişimi",
		day: "Pazar"
	},
	{
		name: "Toki Semt Pazarı",
		province: "MERKEZ",
		city: "ANKARA",
		state: "GÖLBAŞI",
		address: "Eymir Mahallesi Park Eymir Toki Konutları Gölbaşı / ANKARA",
		day: "Pazar"
	},
	{
		name: "Kızılcaşar Açık Semt Pazarı",
		province: "GÖLBAŞI",
		city: "ANKARA",
		state: "GÖLBAŞI",
		address: "Kızılcaşar Mahallesi Turgut Özal Bulvarı üzeri Kızılcaşar muhtarlığı Karşısı Gölbaşı / ANKARA",
		day: "Pazar"
	},
	{
		name: "AŞIKPAŞA PAZARI",
		province: "ESAT",
		city: "ANKARA",
		state: "ÇANKAYA",
		address: "ŞEMSETTİN GÜNALTAY CADDESİ İLE 244.CADDE KÖŞESİ",
		day: "Pazar"
	}
];

export const cityList = [
	"ADANA",
	"ADIYAMAN",
	"AFYONKARAHİSAR",
	"AĞRI",
	"AMASYA",
	"ANKARA",
	"ANTALYA",
	"ARTVİN",
	"AYDIN",
	"BALIKESİR",
	"BİLECİK",
	"BİNGÖL",
	"BİTLİS",
	"BOLU",
	"BURDUR",
	"BURSA",
	"ÇANAKKALE",
	"ÇANKIRI",
	"ÇORUM",
	"DENİZLİ",
	"DİYARBAKIR",
	"EDİRNE",
	"ELAZIĞ",
	"ERZİNCAN",
	"ERZURUM",
	"ESKİŞEHİR",
	"GAZİANTEP",
	"GİRESUN",
	"GÜMÜŞHANE",
	"HAKKARİ",
	"HATAY",
	"IĞDIR",
	"ISPARTA",
	"İSTANBUL",
	"İZMİR",
	"KAHRAMANMARAŞ",
	"KARABÜK",
	"KARAMAN",
	"KARS",
	"KASTAMONU",
	"KAYSERİ",
	"KIRIKKALE",
	"KIRKLARELİ",
	"KIRŞEHİR",
	"KOCAELİ",
	"KONYA",
	"KÜTAHYA",
	"MALATYA",
	"MANİSA",
	"KAHRAMANKAZAN",
	"KEÇİÖREN",
	"MAMAK",
	"NALLIHAN",
	"PURSAKLAR",
	"SİNCAN",
	"YENİMAHALLE",
	"ÇANKAYA",
	"ÇUBUK"
];

export const stateList = [
	"ALTINDAĞ",
	"BEYPAZARI",
	"GÖLBAŞI",
	"KAHRAMANKAZAN",
	"KEÇİÖREN",
	"MAMAK",
	"NALLIHAN",
	"PURSAKLAR",
	"SİNCAN",
	"YENİMAHALLE",
	"ÇANKAYA",
	"ÇUBUK"
];

export const provinceList = [
	"ABİDİNPAŞA",
	"AKDERE",
	"AKTEPE",
	"ALTINDAĞ",
	"AYDINLIKEVLER",
	"AYRANCI",
	"BAHÇELİEVLER",
	"BALGAT",
	"BATIKENT",
	"BAĞLUM",
	"BEYPAZARI",
	"BİLKENT",
	"BOĞAZİÇİ",
	"CEBECİ",
	"DEMETEVLER",
	"DEMİRLİBAHÇE",
	"DİKMEN",
	"ESAT",
	"ESERTEPE(YAYLA)",
	"ETLİK(İNCİRLİ)",
	"GÖLBAŞI",
	"GÜLVEREN",
	"HASKÖY",
	"HÜSEYİNGAZİ",
	"İSKİTLER",
	"KALABA",
	"KARŞIYAKA",
	"KAYAŞ",
	"KIRKONAKLAR",
	"MALTEPE",
	"MAMAK",
	"MERKEZ",
	"MERKEZ KÖYLER",
	"MİSKET",
	"NALLIHAN",
	"OSTİM",
	"PURSAKLAR",
	"SARAYKÖY",
	"SARIYAR",
	"SIHHIYE",
	"SİNCAN",
	"SİTELER",
	"SUSUZ",
	"UFUKTEPE",
	"YAKACIK/YURTÇU",
	"YENİKENT",
	"YENİMAHALLE",
	"YILDIRIMBEYAZIT/DIŞKAPI",
	"YILDIZ",
	"YÜZÜNCÜYILİŞÇİBLOKLARI",
	"ÇAYIRHAN",
	"ÖVEÇLER",
	"ŞEHİTKUBİLAY",
	"ŞENTEPE"
];
